org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
java_version = 17

# Minecraft Properties
minecraft_version=1.20.3
loader_version=0.16.14
loom_version=1.10-SNAPSHOT

# Mod Properties
mod_name = Smootheez Config Lib
modid = scl
mod_description = A library for creating config files for smootheez collection mods.
mod_license = MIT
mod_version = 0.1.8-1.20.3
maven_group = dev.smootheez
archive_base_name = scl

# Dependency Properties
modmenu_version = 9.0.0