name: Publishing Mod

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read Java version
        id: properties
        shell: bash
        run: |
          JAVA_VERSION=$(grep "java_version" gradle.properties | cut -d'=' -f2 | tr -d ' ')
          echo "java_version=$JAVA_VERSION" >> $GITHUB_OUTPUT

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ steps.properties.outputs.java_version }}
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read required properties
        id: properties
        shell: bash
        run: |
          JAVA_VERSION=$(grep "java_version" gradle.properties | cut -d'=' -f2 | tr -d ' ')
          MOD_VERSION=$(grep "mod_version" gradle.properties | cut -d'=' -f2 | tr -d ' ')
          MOD_NAME=$(grep "mod_name" gradle.properties | cut -d'=' -f2- | sed 's/^ //')

          echo "java_version=$JAVA_VERSION" >> $GITHUB_OUTPUT
          echo "mod_version=$MOD_VERSION" >> $GITHUB_OUTPUT
          echo "mod_name=$MOD_NAME" >> $GITHUB_OUTPUT

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: Artifacts
          path: build/libs/

      - name: Find main JAR file
        id: find_jar
        run: |
          JAR_FILE=$(ls build/libs/ | grep -v "sources\|dev" | grep "\.jar$" | head -n 1)
          echo "jar_file=build/libs/$JAR_FILE" >> $GITHUB_OUTPUT
          echo "Found JAR file: $JAR_FILE"

      - name: Upload Mod
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: zLVNfWvA
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: true

          curseforge-id: 1107934
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: ${{ steps.find_jar.outputs.jar_file }}
          name: "${{ steps.properties.outputs.mod_name }} ${{ steps.properties.outputs.mod_version }}"
          version-type: release  # Can be alpha, beta, or release
          version: ${{ steps.get_version.outputs.version }}
          changelog: ${{ github.event.release.body }}

          loaders: fabric
          game-versions: |
            1.20.2
          java: ${{ steps.properties.outputs.java_version }}